name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist  # Or the folder where your built portfolio resides
          branch: gh-pages  # Or any other branch you want to deploy to
